# Generated by Django 2.2 on 2020-09-16 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.IntegerField(default=' ', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('age', models.IntegerField(default=' ')),
                ('gender', models.CharField(default='', max_length=10)),
                ('size', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default=' ', max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.IntegerField(default=' ', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('age', models.IntegerField(default=' ')),
                ('gender', models.CharField(default='', max_length=10)),
                ('size', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default=' ', max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
