# Generated by Django 2.2 on 2020-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adoption_fee',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='weight',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='dog',
            name='adoption_fee',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.CharField(default='', max_length=15),
        ),
    ]
