# Generated by Django 2.2 on 2020-10-02 22:05

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200916_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pets.models.get_image_path),
        ),
    ]
