# Generated by Django 3.0.10 on 2020-11-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donation',
        ),
    ]
