# Generated by Django 2.2 on 2020-10-09 03:44

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201004_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pets.models.get_image_path),
        ),
    ]
