# Generated by Django 3.0.10 on 2020-11-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_delete_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Needing_DatePicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('made_on', models.DateField()),
            ],
        ),
    ]
