# Generated by Django 3.0.10 on 2020-11-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_class_needing_datepicker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_Needing_DatePicker',
        ),
    ]
